#SELECT STATEMENT
SELECT * FROM USER_INFO;
SELECT ID, REGISTRATION_DATE, NAME, PHONE, OPERATING_SYSTEM, OTP_VERIFIED, CITY_ID FROM USER_INFO;

# DISTINCT
SELECT * FROM MENUITEMS;
SELECT DISTINCT PRICE FROM MENUITEMS;

#OPERATORS
# 1. COMPARISON OPERATORS (= equal, > greater than, < less than, >= greater than or equal, <= lessr than or equal, <>/!= not equal to)
SELECT * FROM MENUITEMS WHERE PRICE = 77;
SELECT * FROM MENUITEMS WHERE PRICE < 77;
SELECT * FROM MENUITEMS WHERE PRICE > 77;
SELECT * FROM MENUITEMS WHERE PRICE <= 77;
SELECT * FROM MENUITEMS WHERE PRICE >= 77;
SELECT * FROM MENUITEMS WHERE PRICE <> 77;
SELECT * FROM MENUITEMS WHERE PRICE != 77;

# 2. LOGICAL OPERATORS (AND, OR, NOT)
SELECT * FROM MENUITEMS WHERE PRICE >= 77 AND RESTAURANT_ID = 8;
SELECT * FROM MENUITEMS WHERE PRICE <= 77 OR RESTAURANT_ID = 8;

# 3. SPECIAL OPERATORS (IN, BETWEEN, NOT BETWEEN, LIKE)
SELECT * FROM MENUITEMS WHERE PRICE IN (3,6,77);
SELECT * FROM MENUITEMS WHERE PRICE BETWEEN 50 AND 77;
SELECT * FROM MENUITEMS WHERE PRICE NOT BETWEEN 0 AND 90;
SELECT * FROM USER_INFO WHERE NAME LIKE 'A%';
SELECT * FROM USER_INFO WHERE NAME LIKE '%n';

#ORDER BY (ASC, DESE)
SELECT * FROM MENUITEMS ORDER BY RESTAURANT_ID;
SELECT * FROM MENUITEMS ORDER BY PRICE ASC;
SELECT * FROM MENUITEMS ORDER BY PRICE DESC;
SELECT * FROM MENUITEMS ORDER BY RESTAURANT_ID ASC, PRICE ASC;
SELECT * FROM MENUITEMS ORDER BY RESTAURANT_ID ASC, PRICE DESC;

# LIMIT
SELECT * FROM USER_INFO LIMIT 10;