SELECT * FROM USER_INFO;

# INSERT
# 1.1 INSERT DATA IN OUR TABLE
INSERT INTO USER_INFO
VALUES
	(41, '2024-01-30 12:00:00', 'Asif Antaj Robin', '01312531960', 'Linux', 1, 1);

 # 1.2 INSERT DATA IN OUR TABLE   
INSERT INTO USER_INFO (ID, REGISTRATION_DATE, NAME, PHONE, OPERATING_SYSTEM, OTP_VERIFIED, CITY_ID)
VALUES (42, CURRENT_TIMESTAMP(), 'Robin', '01605186990', 'WINDOWS', 1, 1);

# UPDATE
SELECT * FROM USER_INFO WHERE NAME = 'Robin';
UPDATE USER_INFO SET OPERATING_SYSTEM = 'Windows' WHERE ID = 42;

# DELETE
DELETE FROM USER_INFO WHERE ID BETWEEN 41 AND 42;