# AS Clause
SELECT PHONE AS PHONE_NUMBER FROM USER_INFO;
SELECT * FROM USER_INFO AS USERS;

# INNER JOIN
SELECT * FROM USER_INFO; SELECT * FROM ORDERS;
SELECT * FROM USER_INFO AS A INNER JOIN ORDERS AS B ON A.ID = B.USER_ID;
SELECT DISTINCT A. * FROM USER_INFO AS A INNER JOIN ORDERS AS B ON A.ID = B.USER_ID;

# LEFT OUTER JOIN
SELECT * FROM USER_INFO AS M LEFT JOIN ORDERS AS N ON M.ID = N.USER_ID;
SELECT DISTINCT M. * FROM USER_INFO AS M LEFT JOIN ORDERS AS N ON M.ID = N.USER_ID;
SELECT DISTINCT M. * FROM USER_INFO AS M LEFT JOIN ORDERS AS N ON M.ID = N.USER_ID WHERE N.USER_ID IS NULL;

# RIGHT OUTER JOIN
SELECT * FROM USER_INFO AS M RIGHT JOIN ORDERS AS N ON M.ID = N.USER_ID;
SELECT DISTINCT M. * FROM USER_INFO AS M RIGHT JOIN ORDERS AS N ON M.ID = N.USER_ID;

# RIGHT JOIN
SELECT * FROM USER_INFO AS A RIGHT JOIN CITY AS B ON A.CITY_ID = B.CITY_ID;
SELECT * FROM USER_INFO AS A RIGHT JOIN CITY AS B ON A.CITY_ID = B.CITY_ID WHERE A. CITY_ID IS NULL;

# OUTER JOIN
SELECT ID FROM USER_INFO; SELECT USER_ID FROM ORDERS;
SELECT ID FROM USER_INFO UNION SELECT USER_ID FROM ORDERS;
SELECT ID FROM USER_INFO UNION ALL SELECT USER_ID FROM ORDERS;

# UNIONS

# FULL JOIN
SELECT * FROM USER_INFO AS A LEFT JOIN CITY AS B ON A.CITY_ID = B.CITY_ID UNION ALL
SELECT * FROM USER_INFO AS A RIGHT JOIN CITY AS B ON A.CITY_ID = B.CITY_ID;
--
SELECT * FROM USER_INFO AS A LEFT JOIN CITY AS B ON A.CITY_ID = B.CITY_ID UNION
SELECT * FROM USER_INFO AS A RIGHT JOIN CITY AS B ON A.CITY_ID = B.CITY_ID WHERE A.CITY_ID IS NULL;