# AGGREGATE FUNCTION ( 1.COUNT, 2.SUM, 3.AVG, 4.MAX, 5.MIN)
SELECT * FROM MENUITEMS;
SELECT COUNT(NAME) FROM MENUITEMS;
SELECT COUNT(DISTINCT PRICE) AS 'DIS.PRICE' FROM MENUITEMS;
SELECT SUM(PRICE) AS TOTLA_AMOUNT FROM MENUITEMS;
SELECT AVG(PRICE) AS TOTLA_PRICE, MIN(PRICE) AS LOW_PRICE, MAX(PRICE) AS HIGHT_PRICH FROM MENUITEMS;

# GOOD TO KNOW [ROUND(), COUNT(*)]
SELECT ROUND(AVG(PRICE)) AS TOTLA_PRICE, MIN(PRICE) AS LOW_PRICE, MAX(PRICE) AS HIGHT_PRICH FROM MENUITEMS;
SELECT ROUND(AVG(PRICE),2) AS TOTLA_PRICE, MIN(PRICE) AS LOW_PRICE, MAX(PRICE) AS HIGHT_PRICH FROM MENUITEMS;
SELECT COUNT(NAME) FROM USER_INFO;
SELECT COUNT(ITEM_ID) AS TOTAL_ITEMS, COUNT(*)  FROM MENUITEMS;

#GROUP BY
SELECT * FROM MENUITEMS;
SELECT NAME AS ITEM_NAME, COUNT(RESTAURANT_ID) RESTAURENTS FROM MENUITEMS  GROUP BY ITEM_NAME;
SELECT NAME AS ITEM_NAME, COUNT(RESTAURANT_ID) RESTAURENTS FROM MENUITEMS WHERE NAME IN('ITEM5', 'ITEM3') GROUP BY ITEM_NAME ORDER BY COUNT(RESTAURANT_ID) DESC;
SELECT NAME AS ITEM_NAME, AVG(PRICE), MIN(PRICE), MAX(PRICE) FROM MENUITEMS GROUP BY ITEM_NAME ORDER BY MAX(PRICE) DESC;
SELECT NAME AS ITEM_NAME, RESTAURANT_ID, AVG(PRICE), MIN(PRICE), MAX(PRICE) FROM MENUITEMS GROUP BY ITEM_NAME, RESTAURANT_ID ORDER BY ITEM_NAME ASC;
SELECT NAME AS ITEM_NAME, RESTAURANT_ID, ROUND(AVG(PRICE),2) FROM MENUITEMS GROUP BY ITEM_NAME, RESTAURANT_ID ORDER BY ITEM_NAME ASC;
SELECT NAME AS ITEM_NAME, RESTAURANT_ID, ROUND(AVG(PRICE),2) FROM MENUITEMS GROUP BY 1,2 ORDER BY ITEM_NAME ASC;

-- GROUP BY
SELECT NAME COUNT(RESTAURANT_ID) RESTAURANT_INFO FROM MENUITEMS GROUP BY ITEM_ID;

# HAVING
SELECT NAME AS ITEM_NAME, ROUND(AVG(PRICE),2) FROM MENUITEMS GROUP BY 1 HAVING AVG(PRICE) <50;
SELECT NAME AS ITEM_NAME, MAX(PRICE) FROM MENUITEMS GROUP BY 1 HAVING MAX(PRICE) <50;
SELECT NAME AS ITEM_NAME, MIN(PRICE) FROM MENUITEMS GROUP BY 1 HAVING MIN(PRICE) <50;