SELECT * FROM MENUITEMS;
SELECT AVG(PRICE) AS AVG_PRICE FROM MENUITEMS;

#SBU_QUERIES
# 1
SELECT * FROM MENUITEMS WHERE PRICE > (SELECT AVG(PRICE) AS AVG_PRICE FROM MENUITEMS);

SELECT * FROM ORDERS;
#2
SELECT USER_ID, MIN(DATE(ORDER_DATE)) AS FIRST_ORDER_DATE FROM ORDERS GROUP BY USER_ID;

SELECT FIRST_ORDER_DATE, COUNT(USER_ID) AS NEW_USERS FROM (
SELECT USER_ID, MIN(DATE(ORDER_DATE)) AS FIRST_ORDER_DATE FROM ORDERS GROUP BY USER_ID) AS FIRST_USER_DATA GROUP BY FIRST_ORDER_DATE
ORDER BY NEW_USERS DESC;

#
SELECT * FROM MENUITEMS WHERE PRICE IN (SELECT PRICE FROM MENUITEMS WHERE PRICE>5)
