SELECT * FROM MENUITEMS;

#SBU_QUERIES
SELECT A.NAME, RESTAURANT_ID, PRICE,
CASE WHEN PRICE >10 THEN 'HIGH VALUE' ELSE 'LOW VALUE' END AS PRICE_SENSITIVITY
FROM MENUITEMS A;


# 
SELECT PRICE_SENSITIVITY, COUNT(*) TOTAL_ITEMS FROM (
SELECT A.NAME, RESTAURANT_ID, PRICE,
CASE WHEN PRICE >10 THEN 'HIGH VALUE' ELSE 'LOW VALUE' END AS PRICE_SENSITIVITY
FROM MENUITEMS A ) B
GROUP BY PRICE_SENSITIVITY;

# 
SELECT PRICE_SENSITIVITY, COUNT(*) TOTAL_ITEMS FROM (
SELECT A.NAME, RESTAURANT_ID, PRICE, CASE
WHEN PRICE BETWEEN 0 AND 5 THEN 'LOW VALUE'
WHEN PRICE BETWEEN 6 AND 10 THEN 'MID VALUE'
WHEN PRICE >10 THEN 'HIGH VALUE' ELSE 'UNCONDITIONED' END AS PRICE_SENSITIVITY
FROM MENUITEMS A ) B
GROUP BY PRICE_SENSITIVITY;

# PROBLEM
SELECT * FROM (
SELECT A.NAME, RESTAURANT_ID, PRICE, CASE
WHEN PRICE BETWEEN 1 AND 5 THEN 'LOW VALUE'
WHEN PRICE BETWEEN 6 AND 10 THEN 'MID VALUE'
WHEN PRICE >10 THEN 'HIGH VALUE' ELSE 'UNCONDITIONED' END AS PRICE_SENSITIVITY
FROM MENUITEMS A ) B
WHERE PRICE_SENSITIVITY = 'UNCONDITIONED';

#
SELECT PRICE_SENSITIVITY, COUNT(*) TOTAL_ITEMS FROM (
SELECT A.NAME, RESTAURANT_ID, PRICE, CASE
WHEN PRICE >=0 AND PRICE <=5 THEN 'LOW VALUE'
WHEN PRICE >=6 AND PRICE <= 10 THEN 'MID VALUE'
WHEN PRICE >10 THEN 'HIGH VALUE' ELSE 'UNCONDITIONED' END AS PRICE_SENSITIVITY
FROM MENUITEMS A ) B
GROUP BY PRICE_SENSITIVITY;